import type { Metadata } from "next";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { Providers } from "@/components/Providers";
import { PropsWithChildren } from "react";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <ClerkProvider signInForceRedirectUrl='/login'>
      <html lang='en'>
        <body className={cn(geistSans.variable, "min-h-screen")}>
          <Providers>
            <main className='h-screen'>{children}</main>
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
